project:
  type: website
  output-dir: docs

website:
  title: "PayutSurapinchai.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - favorites.qmd

format:
  html:
    theme: darkly
    mainfont: arial
    fontsize: 1.5rem
    monofont: courier new
    css: styles.css
    toc: true




